# ===============================
# Application
# ===============================
spring.application.name=cdc-synchronization-engine

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/cdc_db
spring.datasource.username=postgres
spring.datasource.password=Nani123@

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# Redis
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# Elasticsearch
# ===============================
spring.elasticsearch.uris=http://localhost:9200

# ===============================
# Swagger
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.enabled=true
